version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hackhub-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackhub
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hackhub-network

networks:
  hackhub-network:


volumes:
  postgres_data:
